// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package web_engine

import (
	"github.com/chenmingyong0423/fnote/server/internal/category"
	"github.com/chenmingyong0423/fnote/server/internal/post"
	"github.com/chenmingyong0423/fnote/server/internal/post_like"
	"github.com/chenmingyong0423/fnote/server/internal/web_engine/internal/service"
	"github.com/chenmingyong0423/fnote/server/internal/web_engine/internal/web"
	"github.com/chenmingyong0423/fnote/server/internal/website_config"
	"github.com/chenmingyong0423/go-eventbus"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitWebEngineModule(eventBus *eventbus.EventBus, websiteConfigMdl *website_config.Module, categoryMdl *category.Module, postMdl *post.Module, postLikeMdl *post_like.Module) *Module {
	webEngineService := service.NewWebEngineService(eventBus, websiteConfigMdl, categoryMdl, postMdl, postLikeMdl)
	webEngineHandler := web.NewWebEngineHandler(webEngineService)
	module := &Module{
		Svc: webEngineService,
		Hdl: webEngineHandler,
	}
	return module
}

// wire.go:

var ConfigProviders = wire.NewSet(web.NewWebEngineHandler, service.NewWebEngineService, wire.Bind(new(service.IWebEngineService), new(*service.WebEngineService)))
